### ISSUE TITLE
用不了了，拉取不了声音

### ISSUE THREAD

**Issue by cikichen** [yy4382/ms-ra-forwarder-for-ifreetime#1]
<img width="446" alt="image" src="https://github.com/yy4382/ms-ra-forwarder-for-ifreetime/assets/1478821/dd02f9e4-62ec-4c3d-96b4-7611bbb70cec">
进去就报错

**Comment by yy4382** [comment]
这个是在那里截的图？网站上吗？还是阅读软件里安装生成的配置是的时候报的错

**Comment by cikichen** [comment]
> 这个是在那里截的图？网站上吗？还是阅读软件里安装生成的配置是的时候报的错

不管是docker还是vercel部署，打完配置页面都会报错

**Comment by cikichen** [comment]
> 这个是在那里截的图？网站上吗？还是阅读软件里安装生成的配置是的时候报的错

网站

**Comment by yy4382** [comment]
检查下你是否能访问这个网址：

https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4

这是获取语音列表时的接口

**Comment by cikichen** [comment]
> 检查下你是否能访问这个网址：
> 
> https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4
> 
> 这是获取语音列表时的接口

![image](https://github.com/yy4382/ms-ra-forwarder-for-ifreetime/assets/1478821/2493a655-a4ff-43dc-88aa-b1f54eb1344b)

![image](https://github.com/yy4382/ms-ra-forwarder-for-ifreetime/assets/1478821/7fa4deed-2d0a-4a6b-8aed-383f9dbadf3b)

**Comment by yy4382** [comment]
能看下在 F12 里是哪个请求失败了（应该是这个，因为只有这个加载不出来会报错），如果是的话，截一下标头 tab 的截图。
![CleanShot 2024-06-22 at 17 22 19@2x](https://github.com/yy4382/ms-ra-forwarder-for-ifreetime/assets/55980292/eae526dc-5607-4f11-99b7-f8788e0422ea)

还有就是在 F12 的控制台里还有什么报错之类

**Comment by cikichen** [comment]
> 能看下在 F12 里是哪个请求失败了（应该是这个，因为只有这个加载不出来会报错），如果是的话，截一下标头 tab 的截图。 ![CleanShot 2024-06-22 at 17 22 19@2x](https://private-user-images.githubusercontent.com/55980292/341957742-eae526dc-5607-4f11-99b7-f8788e0422ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMTMxNjUsIm5iZiI6MTcxOTExMjg2NSwicGF0aCI6Ii81NTk4MDI5Mi8zNDE5NTc3NDItZWFlNTI2ZGMtNTYwNy00ZjExLTk5YjctZjg3ODhlMDQyMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDAzMjEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYmNjZmRkMmY1ZmE5ZDBiY2EwZTliY2E1NGJhYmRmY2ZlZGRlOTZiOTliYjkwMWI5OWUyYzNkNGE1MzFiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1HTbS4AXvEPeWIzpuk6SJjTx7XjSugPxI5x5fwNjOBk)
> 
> 还有就是在 F12 的控制台里还有什么报错之类

被duckduckgo插件屏蔽了
